### ISSUE TITLE
 Which line of code is Formula 1?

### ISSUE THREAD

**Issue by longmalongma** [tea1528/Non-Local-NN-Pytorch#3]
Hi, thanks for you good work, What line of code is Formula 1?What do xi and xj represent in the code?

![image](https://user-images.githubusercontent.com/40291722/118392597-ff3f6500-b66c-11eb-9e60-9ec2d804e330.png)

**Comment by longmalongma** [comment]
> Hi, thanks for you good work, What line of code is Formula 1?What do xi and xj represent in the code?
> 
> ![image](https://user-images.githubusercontent.com/40291722/118392597-ff3f6500-b66c-11eb-9e60-9ec2d804e330.png)

@tea1528

**Comment by tea1528** [comment]
Hi @longmalongma, formula 1 is a generalization of formula 2,3,4,5. The implementation of formula 2 is in https://github.com/tea1528/Non-Local-NN-Pytorch/blob/master/models/non_local.py#L97. x_i and x_j represent the outputs of theta(x) and phi(x) in Figure 2 of the paper.

Hope this helps.

**Comment by longmalongma** [comment]
> Hi @longmalongma, formula 1 is a generalization of formula 2,3,4,5. The implementation of formula 2 is in https://github.com/tea1528/Non-Local-NN-Pytorch/blob/master/models/non_local.py#L97. x_i and x_j represent the outputs of theta(x) and phi(x) in Figure 2 of the paper.
> 
> Hope this helps.

@tea1528 Thank you for your reply. I mean in the video classification task, what can XI and XJ represent respectively?

**Comment by tea1528** [comment]
For video classification, x_i and x_j are each pixel. The operation is conducted in a pairwise manner.
